#!/usr/bin/env bash

tlmapis init
tlmapis adduser --username $DB_USER
echo "
GOCOMMERCE_SITE_URL=${GOCOMMERCE_SITE_URL}
GOCOMMERCE_JWT_SECRET=${GOCOMMERCE_JWT_SECRET}
GOCOMMERCE_DB_DRIVER=postgres
DATABASE_URL="database=${DB_NAME} host=${DB_HOST} port=${DB_PORT} user=${DB_USER} sslmode=verify-ca sslcert=cockroachCerts/client.${DB_USER}.crt sslkey=cockroachCerts/client.${DB_USER}.key sslrootcert=cockroachCerts/ca.crt"
GOCOMMERCE_DB_AUTOMIGRATE=${GOCOMMERCE_DB_AUTOMIGRATE}
GOCOMMERCE_API_HOST=${GOCOMMERCE_API_HOST}
PORT=${PORT}
GOCOMMERCE_MAILER_HOST=${GOCOMMERCE_MAILER_HOST}
GOCOMMERCE_MAILER_PORT=${GOCOMMERCE_MAILER_PORT}
GOCOMMERCE_MAILER_USER=${GOCOMMERCE_MAILER_USER}
GOCOMMERCE_MAILER_PASS=${GOCOMMERCE_MAILER_PASS}
GOCOMMERCE_MAILER_SUBJECTS_ORDER_CONFIRMATION=${GOCOMMERCE_MAILER_SUBJECTS_ORDER_CONFIRMATION}
GOCOMMERCE_MAILER_SUBJECTS_ORDER_RECEIVED=${GOCOMMERCE_MAILER_SUBJECTS_ORDER_RECEIVED}
GOCOMMERCE_PAYMENT_STRIPE_ENABLED=${GOCOMMERCE_PAYMENT_STRIPE_ENABLED}
GOCOMMERCE_PAYMENT_STRIPE_PUBLIC_KEY=${GOCOMMERCE_PAYMENT_STRIPE_PUBLIC_KEY}
GOCOMMERCE_PAYMENT_STRIPE_SECRET_KEY=${GOCOMMERCE_PAYMENT_STRIPE_SECRET_KEY}
GOCOMMERCE_PAYMENT_PAYPAL_ENABLED=${GOCOMMERCE_PAYMENT_PAYPAL_ENABLED}
GOCOMMERCE_PAYMENT_PAYPAL_CLIENT_ID=${GOCOMMERCE_PAYMENT_PAYPAL_CLIENT_ID}
GOCOMMERCE_PAYMENT_PAYPAL_SECRET=${GOCOMMERCE_PAYMENT_PAYPAL_SECRET}
GOCOMMERCE_PAYMENT_PAYPAL_ENV=${GOCOMMERCE_PAYMENT_PAYPAL_ENV}
" >> .env

gocommerce
